"""Post-hoc analysis package for the BCI study."""

from .config import (
    get_subject_group,
    BCI_GROUP_SUBJECTS,
    CONTROL_GROUP_SUBJECTS,
    EXPECTED_SUBJECTS,
    PROJECT_ROOT,
)
from .triggers import (
    load_training_trigger_file,
    compute_training_reaction_times,
    rt_outlier_summary,
)
from .analysis import load_training_analysis_file
from .eeg import (
    baseline_correct_epochs,
    compute_pd_difference_wave,
    compute_pd_positive_auc,
    compute_subject_session_pd_from_condition_averages,
    find_run_gdf_file,
    generate_session_condition_eeg_averages_csv,
    load_compute_and_run_pd_positive_auc_anova,
    load_and_plot_group_pd_pre_post_from_condition_csv,
    load_compute_and_plot_training_pd,
    load_filter_epoch_baseline_correct_and_plot_training,
    load_filter_epoch_and_plot_training_stimulus_epochs,
    load_filter_and_plot_eeg_run_segment,
    plot_group_pd_pre_post,
    run_pd_positive_auc_planned_contrasts,
    run_pd_positive_auc_mixed_anova,
    load_and_plot_eeg_run_segment,
    select_analysis_eeg_channels,
    summarize_group_pd_pre_post,
    summarize_pd_positive_auc,
)
from .consolidated import (
    generate_consolidated_training_csv,
    validate_all_files_comprehensive,
    generate_consolidated_stroop_csv,
    validate_all_stroop_files_comprehensive,
)
from .bci import (
    compute_bci_subject_session_auc,
    compute_bci_combined_threshold_change_session1_to_session5,
    compute_bci_threshold_change_session1_to_session5,
    compute_subject_averaged_posterior_distributions,
    generate_consolidated_bci_csv,
    load_and_run_bci_combined_threshold_change_mixed_anova,
    load_and_plot_bci_combined_threshold_change_session1_to_session5,
    load_and_plot_bci_posterior_distributions,
    load_and_plot_bci_threshold_change_session1_to_session5,
    load_and_run_bci_auc_mixed_anova,
    load_and_plot_bci_auc,
    plot_bci_auc_across_sessions,
    plot_bci_combined_threshold_change_session1_to_session5,
    plot_bci_threshold_change_session1_to_session5,
    plot_subject_averaged_posterior_distributions,
    run_bci_combined_threshold_change_mixed_anova,
    run_bci_auc_mixed_anova,
    summarize_bci_auc_by_group,
    validate_bci_consolidated_dataframe,
)
try:
    from .behavioral import (
        analyze_stroop_accuracy,
        analyze_stroop_effect,
        analyze_stroop_reaction_time,
        analyze_stroop_timeout_exclusions,
        analyze_reaction_time,
        analyze_accuracy_and_timeout,
        analyze_distractor_cost,
        create_behavioral_summary_table,
        create_stroop_accuracy_summary_table,
        load_and_analyze_stroop_effect_data,
        load_and_analyze_stroop_reaction_time_data,
        validate_behavioral_summary,
        validate_stroop_accuracy_summary,
        print_behavioral_summary_checks,
        load_and_analyze_stroop_accuracy_data,
        load_and_summarize_behavioral_data,
        load_and_analyze_stroop_timeout_data,
        summarize_distractor_trial_reaction_time_from_training_csv,
    )
    _BEHAVIORAL_IMPORT_ERROR = None
except ImportError as exc:
    _BEHAVIORAL_IMPORT_ERROR = exc
    print(
        "WARNING: posthoc_analysis.behavioral could not be imported. "
        f"Reason: {exc}. Consolidation utilities remain available."
    )

__all__ = [
    "get_subject_group",
    "BCI_GROUP_SUBJECTS",
    "CONTROL_GROUP_SUBJECTS",
    "EXPECTED_SUBJECTS",
    "PROJECT_ROOT",
    "baseline_correct_epochs",
    "compute_pd_difference_wave",
    "compute_pd_positive_auc",
    "compute_subject_session_pd_from_condition_averages",
    "generate_session_condition_eeg_averages_csv",
    "load_compute_and_run_pd_positive_auc_anova",
    "load_and_plot_group_pd_pre_post_from_condition_csv",
    "load_training_trigger_file",
    "compute_training_reaction_times",
    "rt_outlier_summary",
    "load_training_analysis_file",
    "find_run_gdf_file",
    "load_compute_and_plot_training_pd",
    "load_filter_epoch_baseline_correct_and_plot_training",
    "load_filter_epoch_and_plot_training_stimulus_epochs",
    "load_filter_and_plot_eeg_run_segment",
    "plot_group_pd_pre_post",
    "run_pd_positive_auc_planned_contrasts",
    "run_pd_positive_auc_mixed_anova",
    "load_and_plot_eeg_run_segment",
    "select_analysis_eeg_channels",
    "summarize_group_pd_pre_post",
    "summarize_pd_positive_auc",
    "generate_consolidated_training_csv",
    "validate_all_files_comprehensive",
    "generate_consolidated_stroop_csv",
    "validate_all_stroop_files_comprehensive",
    "compute_bci_subject_session_auc",
    "compute_bci_combined_threshold_change_session1_to_session5",
    "compute_bci_threshold_change_session1_to_session5",
    "compute_subject_averaged_posterior_distributions",
    "generate_consolidated_bci_csv",
    "load_and_run_bci_combined_threshold_change_mixed_anova",
    "load_and_plot_bci_combined_threshold_change_session1_to_session5",
    "load_and_plot_bci_posterior_distributions",
    "load_and_plot_bci_threshold_change_session1_to_session5",
    "load_and_run_bci_auc_mixed_anova",
    "load_and_plot_bci_auc",
    "plot_bci_auc_across_sessions",
    "plot_bci_combined_threshold_change_session1_to_session5",
    "plot_bci_threshold_change_session1_to_session5",
    "plot_subject_averaged_posterior_distributions",
    "run_bci_combined_threshold_change_mixed_anova",
    "run_bci_auc_mixed_anova",
    "summarize_bci_auc_by_group",
    "validate_bci_consolidated_dataframe",
]

if _BEHAVIORAL_IMPORT_ERROR is None:
    __all__.extend([
        "analyze_stroop_accuracy",
        "analyze_stroop_effect",
        "analyze_stroop_reaction_time",
        "analyze_stroop_timeout_exclusions",
        "analyze_reaction_time",
        "analyze_accuracy_and_timeout",
        "analyze_distractor_cost",
        "create_behavioral_summary_table",
        "create_stroop_accuracy_summary_table",
        "load_and_analyze_stroop_effect_data",
        "load_and_analyze_stroop_reaction_time_data",
        "validate_behavioral_summary",
        "validate_stroop_accuracy_summary",
        "print_behavioral_summary_checks",
        "load_and_analyze_stroop_accuracy_data",
        "load_and_summarize_behavioral_data",
        "load_and_analyze_stroop_timeout_data",
        "summarize_distractor_trial_reaction_time_from_training_csv",
    ])
